float32 accelerationlongitudinalerramp #(Unused) Error amplitude of longitudinal acceleration
uint8 accelerationlongitudinalerramp_invalidflag #(Unused) Invalid Flags AccelLongErrAmp 
uint8 qualifieraccelerationlongitudinal #(Unused) Longitudinal Acceleration Qualifier 
float32 accelerationlongitudinal #Longitudinal Acceleration
uint8 accelerationlongitudinal_invalidflag #(Unused) Invalid Flag Longitudinal Acceleration 
uint8 accelerationlongitudinaleventdataqualifier #(Unused) Event Data Qualifier Longitudinal Acceleration 

