float32 accelerationlateralerramp #(Unused) Error Amplitude of Lateral Acceleration 
uint8 accelerationlateralerramp_invalidflag #(Unused) Invalid Flags AccelLatErrAmp  
uint8 qualifieraccelerationlateral #(Unused) Lateral Acceleration Qualifier 
float32 accelerationlateral #Lateral Acceleration
uint8 accelerationlateral_invalidflag #(Unused) Invalid Flag Lateral Acceleration 
uint8 accelerationlateraleventdataqualifier #(Unused) Event Data Qualifier Lateral Acceleration 