float32 f_azimuthangle #Unaligned Detection Azimuth Angle
float32 f_azimuthanglestd #Azimuth Angle Std
uint8 u_invalidflags #Detection Invalid Flags 
float32 f_elevationangle #Unaligned Detection Elevation Angle
float32 f_elevationanglestd #Elevation Angle Std
float32 f_range #Detection Radial Distance
float32 f_rangestd #Radial Distance Std
float32 f_rangerate #Detection Radial Velocity
float32 f_rangeratestd #Radial Velocity Std
int8 s_rcs #Detection RCS
uint16 u_measurementid #Detection ID
uint8 u_positivepredictivevalue #Existence Probability
uint8 u_classification #Detection Classification
uint8 u_multitargetprobabilitym #Multi-Target Probability
uint16 u_objectid #Associated Object ID
uint8 u_ambiguityflag #Probability for resolved velocity ambiguity
uint16 u_sortindex #tbd