uint8 qualifiersteeringanglefrontaxle #(unused) Steering angle front axle qualifier
float32 steeringanglefrontaxleerramp #(unused) Error amplitude of steering angle front axle
uint8 steeringanglefrontaxleerramp_invalidflag #(unused) Invalid flag steering angle front axle errAmp
float32 steeringanglefrontaxle #Steering angle front axle
uint8 steeringanglefrontaxle_invalidflag #(unused) Invalid flag steeting angle front axle
uint8 steeringanglefrontaxleeventdataqualifier #(unused) Event data qualifier steering angle front axle